name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        #### Before opening a bug report, please search for the behaviour in the existing issues.
        Please discuss the issue in the community forum on [VPU](https://vpuniverse.com/files/file/2119-b2s-designer) or [VPF](https://www.vpforums.org/index.php?showforum=89) before filing a bug.
        
        ---
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information:
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of B2S Designer are you using?
      placeholder: 2.1.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/vpinball/b2s-designer/blob/master/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
