name: Feature request
description: File a bug report.
title: "A clear and concise title"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Before opening a feature request, please search for the behaviour in the existing issues
        ### and discuss it in the community forums on [vpuniverse](https://vpuniverse.com/files/file/2119-b2s-designer) or [vpforums](https://www.vpforums.org/index.php?showforum=89).
        
        ---
        Thank you for taking the time to add feature request. To address this as fast as possible, we need some information:
  - type: textarea
    id: steps
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of the problem. You can paste screenshots 📸 in the fields.
      placeholder: |
        Steps to reproduce the your problem:
        1. Go to ...
        2. Click on ...
        3. See screenshot
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like ✅
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of B2S Designer are you using?
      placeholder: 2.1.0
    validations:
      required: true