blank_issues_enabled: true
contact_links:
  - name: B2S Designer community forum on VPU
    url: https://vpuniverse.com/files/file/2119-b2s-designer
    about: Before adding an issue, please ask and answer questions here.
